### ISSUE TITLE
is the shadow stack implementation available?

### ISSUE THREAD

**Issue by Ruturaj4** [utds3lab/multiverse#9]
I read the paper: Superset Disassembly: Statically Rewriting x86 Binaries Without Heuristics. And I found the shadow stack implementation example (mentioned in security applications section) really interesting. Is this available in open source by any chance, if not could you please make it available? Thanks so much! It will be really helpful in my research.

p.s.: I am a phd candidate and sec researcher @ university of kansas.

**Comment by baumane** [comment]
Yes, the shadow stack implementation can be found on this branch:
https://github.com/utds3lab/multiverse/tree/shadow
It is a number of commits behind the master branch, and therefore may have bugs not present in master.  You can check the diffs for the last two commits in that branch for the changes I made to add the shadow stack.  I hope this helps!

**Comment by Ruturaj4** [comment]
@baumane thanks so much for your quick comment and help. I appreciate it.
